import type { Product, Category, Review } from "./types"

export const categories: Category[] = [
  {
    id: 1,
    name: "Fruits",
    icon: "🍎",
    color: "bg-red-100 text-red-800",
    description: "Fresh, organic fruits",
    productCount: 45,
  },
  {
    id: 2,
    name: "Vegetables",
    icon: "🥕",
    color: "bg-orange-100 text-orange-800",
    description: "Farm-fresh vegetables",
    productCount: 67,
  },
  {
    id: 3,
    name: "Dairy",
    icon: "🥛",
    color: "bg-blue-100 text-blue-800",
    description: "Fresh dairy products",
    productCount: 23,
  },
  {
    id: 4,
    name: "Meat",
    icon: "🥩",
    color: "bg-red-100 text-red-800",
    description: "Premium quality meat",
    productCount: 34,
  },
  {
    id: 5,
    name: "Bakery",
    icon: "🍞",
    color: "bg-yellow-100 text-yellow-800",
    description: "Fresh baked goods",
    productCount: 28,
  },
  {
    id: 6,
    name: "Beverages",
    icon: "🥤",
    color: "bg-purple-100 text-purple-800",
    description: "Refreshing drinks",
    productCount: 56,
  },
  {
    id: 7,
    name: "Snacks",
    icon: "🍿",
    color: "bg-yellow-100 text-yellow-800",
    description: "Healthy snacks",
    productCount: 89,
  },
  {
    id: 8,
    name: "Frozen",
    icon: "🧊",
    color: "bg-blue-100 text-blue-800",
    description: "Frozen foods",
    productCount: 42,
  },
]

export const products: Product[] = [
  {
    id: 1,
    name: "Fresh Organic Apples",
    price: 4.99,
    originalPrice: 6.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.5,
    reviewCount: 128,
    category: "Fruits",
    brand: "Organic Farm",
    inStock: true,
    stockCount: 24,
    description:
      "Premium quality organic apples sourced directly from certified organic farms. These crisp, sweet apples are perfect for snacking, baking, or adding to your favorite recipes. Rich in fiber, vitamins, and antioxidants.",
    features: [
      "100% Organic certified",
      "Locally sourced",
      "No pesticides or chemicals",
      "Fresh picked daily",
      "Rich in vitamins and fiber",
    ],
    nutritionFacts: {
      calories: 95,
      carbs: "25g",
      fiber: "4g",
      sugar: "19g",
      protein: "0.5g",
      fat: "0.3g",
    },
    tags: ["organic", "fresh", "healthy"],
    weight: "1 lb",
    origin: "Local Farm",
  },
  {
    id: 2,
    name: "Premium Avocados",
    price: 3.49,
    originalPrice: 4.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.8,
    reviewCount: 89,
    category: "Fruits",
    brand: "Fresh Valley",
    inStock: true,
    stockCount: 18,
    description:
      "Perfectly ripe avocados with creamy texture and rich flavor. Ideal for guacamole, toast, salads, or eating fresh.",
    features: [
      "Hand-picked for ripeness",
      "Rich in healthy fats",
      "High in potassium",
      "Versatile ingredient",
      "Naturally gluten-free",
    ],
    nutritionFacts: {
      calories: 234,
      carbs: "12g",
      fiber: "10g",
      sugar: "1g",
      protein: "3g",
      fat: "21g",
    },
    tags: ["healthy fats", "fresh", "versatile"],
    weight: "Each",
    origin: "California",
  },
  {
    id: 3,
    name: "Organic Baby Spinach",
    price: 2.99,
    originalPrice: 3.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg"],
    rating: 4.3,
    reviewCount: 67,
    category: "Vegetables",
    brand: "Green Fields",
    inStock: true,
    stockCount: 32,
    description:
      "Tender, fresh organic baby spinach leaves. Perfect for salads, smoothies, or cooking. Packed with iron, vitamins, and minerals.",
    features: [
      "Organic certified",
      "Pre-washed and ready to eat",
      "High in iron and vitamins",
      "Tender baby leaves",
      "Versatile for cooking or raw",
    ],
    nutritionFacts: {
      calories: 23,
      carbs: "4g",
      fiber: "2g",
      sugar: "0g",
      protein: "3g",
      fat: "0g",
    },
    tags: ["organic", "leafy greens", "healthy"],
    weight: "5 oz",
    origin: "Local Farm",
  },
  {
    id: 4,
    name: "Fresh Atlantic Salmon",
    price: 12.99,
    originalPrice: 15.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.7,
    reviewCount: 156,
    category: "Meat",
    brand: "Ocean Fresh",
    inStock: true,
    stockCount: 8,
    description:
      "Premium Atlantic salmon fillet, sustainably sourced. Rich in omega-3 fatty acids and perfect for grilling, baking, or pan-searing.",
    features: ["Sustainably sourced", "Rich in omega-3", "Fresh, never frozen", "Skin-on fillet", "Restaurant quality"],
    nutritionFacts: {
      calories: 206,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "22g",
      fat: "12g",
    },
    tags: ["seafood", "omega-3", "protein"],
    weight: "1 lb",
    origin: "Atlantic Ocean",
  },
  {
    id: 5,
    name: "Artisan Sourdough Bread",
    price: 5.49,
    originalPrice: 6.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg"],
    rating: 4.6,
    reviewCount: 94,
    category: "Bakery",
    brand: "Local Bakery",
    inStock: true,
    stockCount: 12,
    description:
      "Handcrafted sourdough bread with a crispy crust and soft, tangy interior. Made with traditional fermentation methods.",
    features: [
      "Traditional sourdough starter",
      "Hand-shaped loaves",
      "No artificial preservatives",
      "Crispy crust",
      "Perfect for toasting",
    ],
    nutritionFacts: {
      calories: 120,
      carbs: "23g",
      fiber: "1g",
      sugar: "1g",
      protein: "4g",
      fat: "1g",
    },
    tags: ["artisan", "sourdough", "fresh baked"],
    weight: "1.5 lb",
    origin: "Local Bakery",
  },
  {
    id: 6,
    name: "Organic Whole Milk",
    price: 4.29,
    originalPrice: 4.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg"],
    rating: 4.4,
    reviewCount: 203,
    category: "Dairy",
    brand: "Happy Cows",
    inStock: true,
    stockCount: 45,
    description:
      "Fresh organic whole milk from grass-fed cows. Rich, creamy taste with no artificial hormones or antibiotics.",
    features: [
      "From grass-fed cows",
      "No rBST hormones",
      "Organic certified",
      "Rich and creamy",
      "Glass bottle packaging",
    ],
    nutritionFacts: {
      calories: 150,
      carbs: "12g",
      fiber: "0g",
      sugar: "12g",
      protein: "8g",
      fat: "8g",
    },
    tags: ["organic", "dairy", "grass-fed"],
    weight: "1 gallon",
    origin: "Local Dairy",
  },
]

export const reviews: Review[] = [
  {
    id: 1,
    userId: "user1",
    userName: "Sarah Johnson",
    rating: 5,
    comment: "Amazing quality! Super fresh and crispy. Will definitely order again.",
    date: "2024-01-15",
    verified: true,
    helpful: 12,
  },
  {
    id: 2,
    userId: "user2",
    userName: "Mike Chen",
    rating: 4,
    comment: "Good apples, arrived fresh. Packaging could be better but overall satisfied.",
    date: "2024-01-10",
    verified: true,
    helpful: 8,
  },
  {
    id: 3,
    userId: "user3",
    userName: "Emma Davis",
    rating: 5,
    comment: "Best organic apples I've had! Perfect for my kids' lunch boxes.",
    date: "2024-01-08",
    verified: true,
    helpful: 15,
  },
]

export const promoSlides = [
  {
    id: 1,
    title: "Fresh Produce Sale",
    subtitle: "Up to 30% off on fruits & vegetables",
    image: "/placeholder.svg",
    color: "bg-green-500",
    cta: "Shop Produce",
    link: "/category/1",
  },
  {
    id: 2,
    title: "Free Delivery",
    subtitle: "On orders over $50",
    image: "/placeholder.svg",
    color: "bg-blue-500",
    cta: "Start Shopping",
    link: "/",
  },
  {
    id: 3,
    title: "Organic Week",
    subtitle: "Special prices on organic products",
    image: "/placeholder.svg",
    color: "bg-yellow-500",
    cta: "Shop Organic",
    link: "/category/organic",
  },
]
