import type { Product, Category, Review } from "./types"

export const categories: Category[] = [
  {
    id: 1,
    name: "Fruits",
    icon: "🍎",
    color: "bg-red-100 text-red-800",
    description: "Fresh, organic fruits",
    productCount: 45,
  },
  {
    id: 2,
    name: "Vegetables",
    icon: "🥕",
    color: "bg-orange-100 text-orange-800",
    description: "Farm-fresh vegetables",
    productCount: 67,
  },
  {
    id: 3,
    name: "Dairy",
    icon: "🥛",
    color: "bg-blue-100 text-blue-800",
    description: "Fresh dairy products",
    productCount: 23,
  },
  {
    id: 4,
    name: "Meat",
    icon: "🥩",
    color: "bg-red-100 text-red-800",
    description: "Premium quality meat",
    productCount: 34,
  },
  {
    id: 5,
    name: "Bakery",
    icon: "🍞",
    color: "bg-yellow-100 text-yellow-800",
    description: "Fresh baked goods",
    productCount: 28,
  },
  {
    id: 6,
    name: "Beverages",
    icon: "🥤",
    color: "bg-purple-100 text-purple-800",
    description: "Refreshing drinks",
    productCount: 56,
  },
]

export const products: Product[] = [
  // Fruits
  {
    id: 1,
    name: "Fresh Organic Apples",
    price: 4.99,
    originalPrice: 6.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300", "/placeholder.svg?height=300&width=300"],
    rating: 4.5,
    reviewCount: 128,
    category: "Fruits",
    categoryId: 1,
    brand: "Organic Farm",
    inStock: true,
    stockCount: 24,
    description: "Premium quality organic apples sourced directly from certified organic farms.",
    features: ["100% Organic certified", "Locally sourced", "No pesticides"],
    nutritionFacts: {
      calories: 95,
      carbs: "25g",
      fiber: "4g",
      sugar: "19g",
      protein: "0.5g",
      fat: "0.3g",
    },
    tags: ["organic", "fresh", "healthy"],
    weight: "1 lb",
    origin: "Local Farm",
  },
  {
    id: 2,
    name: "Premium Avocados",
    price: 3.49,
    originalPrice: 4.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.8,
    reviewCount: 89,
    category: "Fruits",
    categoryId: 1,
    brand: "Fresh Valley",
    inStock: true,
    stockCount: 18,
    description: "Perfectly ripe avocados with creamy texture and rich flavor.",
    features: ["Hand-picked for ripeness", "Rich in healthy fats"],
    nutritionFacts: {
      calories: 234,
      carbs: "12g",
      fiber: "10g",
      sugar: "1g",
      protein: "3g",
      fat: "21g",
    },
    tags: ["healthy fats", "fresh"],
    weight: "Each",
    origin: "California",
  },
  {
    id: 3,
    name: "Sweet Bananas",
    price: 2.99,
    originalPrice: 3.49,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.6,
    reviewCount: 156,
    category: "Fruits",
    categoryId: 1,
    brand: "Tropical Fresh",
    inStock: true,
    stockCount: 45,
    description: "Sweet, ripe bananas perfect for snacking or smoothies.",
    features: ["High in potassium", "Natural energy boost"],
    nutritionFacts: {
      calories: 105,
      carbs: "27g",
      fiber: "3g",
      sugar: "14g",
      protein: "1g",
      fat: "0.4g",
    },
    tags: ["sweet", "energy"],
    weight: "1 bunch",
    origin: "Ecuador",
  },
  {
    id: 4,
    name: "Fresh Strawberries",
    price: 5.99,
    originalPrice: 7.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.7,
    reviewCount: 203,
    category: "Fruits",
    categoryId: 1,
    brand: "Berry Fresh",
    inStock: true,
    stockCount: 28,
    description: "Juicy, sweet strawberries bursting with flavor.",
    features: ["High in vitamin C", "Antioxidant rich"],
    nutritionFacts: {
      calories: 49,
      carbs: "12g",
      fiber: "3g",
      sugar: "7g",
      protein: "1g",
      fat: "0.5g",
    },
    tags: ["vitamin C", "antioxidants"],
    weight: "1 lb",
    origin: "California",
  },

  // Vegetables
  {
    id: 5,
    name: "Organic Baby Spinach",
    price: 2.99,
    originalPrice: 3.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.3,
    reviewCount: 67,
    category: "Vegetables",
    categoryId: 2,
    brand: "Green Fields",
    inStock: true,
    stockCount: 32,
    description: "Tender, fresh organic baby spinach leaves.",
    features: ["Organic certified", "Pre-washed", "High in iron"],
    nutritionFacts: {
      calories: 23,
      carbs: "4g",
      fiber: "2g",
      sugar: "0g",
      protein: "3g",
      fat: "0g",
    },
    tags: ["organic", "leafy greens"],
    weight: "5 oz",
    origin: "Local Farm",
  },
  {
    id: 6,
    name: "Fresh Carrots",
    price: 1.99,
    originalPrice: 2.49,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.4,
    reviewCount: 89,
    category: "Vegetables",
    categoryId: 2,
    brand: "Farm Fresh",
    inStock: true,
    stockCount: 56,
    description: "Crisp, sweet carrots perfect for snacking or cooking.",
    features: ["High in beta-carotene", "Crunchy texture"],
    nutritionFacts: {
      calories: 41,
      carbs: "10g",
      fiber: "3g",
      sugar: "5g",
      protein: "1g",
      fat: "0.2g",
    },
    tags: ["beta-carotene", "crunchy"],
    weight: "2 lbs",
    origin: "Local Farm",
  },
  {
    id: 7,
    name: "Bell Peppers Mix",
    price: 4.49,
    originalPrice: 5.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.5,
    reviewCount: 112,
    category: "Vegetables",
    categoryId: 2,
    brand: "Rainbow Farms",
    inStock: true,
    stockCount: 34,
    description: "Colorful mix of red, yellow, and green bell peppers.",
    features: ["Vitamin C rich", "Colorful variety"],
    nutritionFacts: {
      calories: 31,
      carbs: "7g",
      fiber: "3g",
      sugar: "5g",
      protein: "1g",
      fat: "0.3g",
    },
    tags: ["vitamin C", "colorful"],
    weight: "3 pack",
    origin: "Local Farm",
  },
  {
    id: 8,
    name: "Fresh Broccoli",
    price: 3.49,
    originalPrice: 4.29,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.2,
    reviewCount: 78,
    category: "Vegetables",
    categoryId: 2,
    brand: "Green Valley",
    inStock: true,
    stockCount: 23,
    description: "Fresh, crisp broccoli crowns packed with nutrients.",
    features: ["High in fiber", "Vitamin K rich"],
    nutritionFacts: {
      calories: 34,
      carbs: "7g",
      fiber: "3g",
      sugar: "2g",
      protein: "3g",
      fat: "0.4g",
    },
    tags: ["fiber", "vitamin K"],
    weight: "1 head",
    origin: "California",
  },

  // Dairy
  {
    id: 9,
    name: "Organic Whole Milk",
    price: 4.29,
    originalPrice: 4.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.4,
    reviewCount: 203,
    category: "Dairy",
    categoryId: 3,
    brand: "Happy Cows",
    inStock: true,
    stockCount: 45,
    description: "Fresh organic whole milk from grass-fed cows.",
    features: ["From grass-fed cows", "No rBST hormones"],
    nutritionFacts: {
      calories: 150,
      carbs: "12g",
      fiber: "0g",
      sugar: "12g",
      protein: "8g",
      fat: "8g",
    },
    tags: ["organic", "grass-fed"],
    weight: "1 gallon",
    origin: "Local Dairy",
  },
  {
    id: 10,
    name: "Greek Yogurt",
    price: 5.99,
    originalPrice: 7.49,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.6,
    reviewCount: 167,
    category: "Dairy",
    categoryId: 3,
    brand: "Mediterranean",
    inStock: true,
    stockCount: 28,
    description: "Thick, creamy Greek yogurt with live cultures.",
    features: ["High in protein", "Live probiotics"],
    nutritionFacts: {
      calories: 100,
      carbs: "6g",
      fiber: "0g",
      sugar: "6g",
      protein: "17g",
      fat: "0g",
    },
    tags: ["protein", "probiotics"],
    weight: "32 oz",
    origin: "Local Dairy",
  },
  {
    id: 11,
    name: "Aged Cheddar Cheese",
    price: 6.99,
    originalPrice: 8.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.7,
    reviewCount: 134,
    category: "Dairy",
    categoryId: 3,
    brand: "Artisan Cheese",
    inStock: true,
    stockCount: 19,
    description: "Sharp, aged cheddar cheese with rich flavor.",
    features: ["Aged 12 months", "Rich flavor"],
    nutritionFacts: {
      calories: 113,
      carbs: "1g",
      fiber: "0g",
      sugar: "0g",
      protein: "7g",
      fat: "9g",
    },
    tags: ["aged", "sharp"],
    weight: "8 oz",
    origin: "Vermont",
  },
  {
    id: 12,
    name: "Farm Fresh Eggs",
    price: 3.99,
    originalPrice: 4.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.8,
    reviewCount: 289,
    category: "Dairy",
    categoryId: 3,
    brand: "Free Range Farm",
    inStock: true,
    stockCount: 67,
    description: "Fresh eggs from free-range hens.",
    features: ["Free-range", "Omega-3 enriched"],
    nutritionFacts: {
      calories: 70,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "6g",
      fat: "5g",
    },
    tags: ["free-range", "omega-3"],
    weight: "12 count",
    origin: "Local Farm",
  },

  // Meat
  {
    id: 13,
    name: "Fresh Atlantic Salmon",
    price: 12.99,
    originalPrice: 15.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.7,
    reviewCount: 156,
    category: "Meat",
    categoryId: 4,
    brand: "Ocean Fresh",
    inStock: true,
    stockCount: 8,
    description: "Premium Atlantic salmon fillet, sustainably sourced.",
    features: ["Sustainably sourced", "Rich in omega-3"],
    nutritionFacts: {
      calories: 206,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "22g",
      fat: "12g",
    },
    tags: ["seafood", "omega-3"],
    weight: "1 lb",
    origin: "Atlantic Ocean",
  },
  {
    id: 14,
    name: "Grass-Fed Ground Beef",
    price: 8.99,
    originalPrice: 10.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.5,
    reviewCount: 198,
    category: "Meat",
    categoryId: 4,
    brand: "Ranch Prime",
    inStock: true,
    stockCount: 15,
    description: "Lean ground beef from grass-fed cattle.",
    features: ["Grass-fed", "85% lean"],
    nutritionFacts: {
      calories: 250,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "26g",
      fat: "15g",
    },
    tags: ["grass-fed", "lean"],
    weight: "1 lb",
    origin: "Local Ranch",
  },
  {
    id: 15,
    name: "Organic Chicken Breast",
    price: 9.99,
    originalPrice: 12.49,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.6,
    reviewCount: 223,
    category: "Meat",
    categoryId: 4,
    brand: "Free Range Farms",
    inStock: true,
    stockCount: 22,
    description: "Tender, organic chicken breast from free-range chickens.",
    features: ["Organic certified", "Free-range"],
    nutritionFacts: {
      calories: 165,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "31g",
      fat: "3.6g",
    },
    tags: ["organic", "free-range"],
    weight: "1 lb",
    origin: "Local Farm",
  },
  {
    id: 16,
    name: "Wild-Caught Shrimp",
    price: 14.99,
    originalPrice: 17.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.4,
    reviewCount: 87,
    category: "Meat",
    categoryId: 4,
    brand: "Ocean Harvest",
    inStock: true,
    stockCount: 12,
    description: "Fresh wild-caught shrimp, peeled and deveined.",
    features: ["Wild-caught", "Peeled & deveined"],
    nutritionFacts: {
      calories: 84,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "18g",
      fat: "1g",
    },
    tags: ["wild-caught", "seafood"],
    weight: "1 lb",
    origin: "Gulf Coast",
  },

  // Bakery
  {
    id: 17,
    name: "Artisan Sourdough Bread",
    price: 5.49,
    originalPrice: 6.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.6,
    reviewCount: 94,
    category: "Bakery",
    categoryId: 5,
    brand: "Local Bakery",
    inStock: true,
    stockCount: 12,
    description: "Handcrafted sourdough bread with crispy crust.",
    features: ["Traditional starter", "Hand-shaped"],
    nutritionFacts: {
      calories: 120,
      carbs: "23g",
      fiber: "1g",
      sugar: "1g",
      protein: "4g",
      fat: "1g",
    },
    tags: ["artisan", "sourdough"],
    weight: "1.5 lb",
    origin: "Local Bakery",
  },
  {
    id: 18,
    name: "Fresh Croissants",
    price: 4.99,
    originalPrice: 6.49,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.5,
    reviewCount: 156,
    category: "Bakery",
    categoryId: 5,
    brand: "French Bakery",
    inStock: true,
    stockCount: 18,
    description: "Buttery, flaky croissants baked fresh daily.",
    features: ["Buttery layers", "Fresh daily"],
    nutritionFacts: {
      calories: 231,
      carbs: "26g",
      fiber: "1g",
      sugar: "3g",
      protein: "5g",
      fat: "12g",
    },
    tags: ["buttery", "flaky"],
    weight: "4 pack",
    origin: "Local Bakery",
  },
  {
    id: 19,
    name: "Whole Wheat Bagels",
    price: 3.99,
    originalPrice: 4.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.3,
    reviewCount: 78,
    category: "Bakery",
    categoryId: 5,
    brand: "Healthy Grains",
    inStock: true,
    stockCount: 25,
    description: "Nutritious whole wheat bagels with seeds.",
    features: ["Whole wheat", "High fiber"],
    nutritionFacts: {
      calories: 245,
      carbs: "48g",
      fiber: "4g",
      sugar: "5g",
      protein: "10g",
      fat: "2g",
    },
    tags: ["whole wheat", "fiber"],
    weight: "6 pack",
    origin: "Local Bakery",
  },
  {
    id: 20,
    name: "Chocolate Muffins",
    price: 6.99,
    originalPrice: 8.49,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.7,
    reviewCount: 203,
    category: "Bakery",
    categoryId: 5,
    brand: "Sweet Treats",
    inStock: true,
    stockCount: 14,
    description: "Rich chocolate muffins with chocolate chips.",
    features: ["Double chocolate", "Moist texture"],
    nutritionFacts: {
      calories: 420,
      carbs: "58g",
      fiber: "3g",
      sugar: "32g",
      protein: "6g",
      fat: "18g",
    },
    tags: ["chocolate", "sweet"],
    weight: "4 pack",
    origin: "Local Bakery",
  },

  // Beverages
  {
    id: 21,
    name: "Fresh Orange Juice",
    price: 4.99,
    originalPrice: 5.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.5,
    reviewCount: 167,
    category: "Beverages",
    categoryId: 6,
    brand: "Citrus Fresh",
    inStock: true,
    stockCount: 34,
    description: "Freshly squeezed orange juice, no pulp.",
    features: ["Freshly squeezed", "No pulp"],
    nutritionFacts: {
      calories: 112,
      carbs: "26g",
      fiber: "0g",
      sugar: "21g",
      protein: "2g",
      fat: "0.5g",
    },
    tags: ["fresh", "vitamin C"],
    weight: "64 oz",
    origin: "Florida",
  },
  {
    id: 22,
    name: "Sparkling Water",
    price: 2.99,
    originalPrice: 3.99,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.3,
    reviewCount: 89,
    category: "Beverages",
    categoryId: 6,
    brand: "Pure Springs",
    inStock: true,
    stockCount: 56,
    description: "Refreshing sparkling water with natural bubbles.",
    features: ["Natural bubbles", "Zero calories"],
    nutritionFacts: {
      calories: 0,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "0g",
      fat: "0g",
    },
    tags: ["sparkling", "zero calories"],
    weight: "12 pack",
    origin: "Natural Springs",
  },
  {
    id: 23,
    name: "Green Tea",
    price: 3.49,
    originalPrice: 4.29,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.4,
    reviewCount: 112,
    category: "Beverages",
    categoryId: 6,
    brand: "Zen Tea",
    inStock: true,
    stockCount: 42,
    description: "Premium green tea with antioxidants.",
    features: ["Antioxidant rich", "Organic"],
    nutritionFacts: {
      calories: 2,
      carbs: "0g",
      fiber: "0g",
      sugar: "0g",
      protein: "0g",
      fat: "0g",
    },
    tags: ["antioxidants", "organic"],
    weight: "20 bags",
    origin: "Japan",
  },
  {
    id: 24,
    name: "Cold Brew Coffee",
    price: 5.99,
    originalPrice: 7.49,
    image: "/placeholder.svg?height=300&width=300",
    images: ["/placeholder.svg?height=300&width=300"],
    rating: 4.6,
    reviewCount: 234,
    category: "Beverages",
    categoryId: 6,
    brand: "Roast Masters",
    inStock: true,
    stockCount: 28,
    description: "Smooth cold brew coffee, ready to drink.",
    features: ["Smooth taste", "Ready to drink"],
    nutritionFacts: {
      calories: 5,
      carbs: "1g",
      fiber: "0g",
      sugar: "0g",
      protein: "1g",
      fat: "0g",
    },
    tags: ["cold brew", "smooth"],
    weight: "32 oz",
    origin: "Local Roastery",
  },
]

export const reviews: Review[] = [
  {
    id: 1,
    userId: "user1",
    userName: "Sarah Johnson",
    rating: 5,
    comment: "Amazing quality! Super fresh and crispy. Will definitely order again.",
    date: "2024-01-15",
    verified: true,
    helpful: 12,
  },
  {
    id: 2,
    userId: "user2",
    userName: "Mike Chen",
    rating: 4,
    comment: "Good apples, arrived fresh. Packaging could be better but overall satisfied.",
    date: "2024-01-10",
    verified: true,
    helpful: 8,
  },
  {
    id: 3,
    userId: "user3",
    userName: "Emma Davis",
    rating: 5,
    comment: "Best organic apples I've had! Perfect for my kids' lunch boxes.",
    date: "2024-01-08",
    verified: true,
    helpful: 15,
  },
]
